USE InsigniaDW;

-- copy of the Insignia_staging table with the name Insignia_staging_copy
CREATE TABLE Insignia_staging_copy (
    InvoiceId INT,
    Description VARCHAR(255),
    Quantity INT,
    Unit_Price DECIMAL(18, 2),
    Tax_Rate DECIMAL(5, 2),
    Total_Excluding_Tax DECIMAL(18, 2),
    Tax_Amount DECIMAL(18, 2),
    Profit DECIMAL(18, 2),
    Total_Including_Tax DECIMAL(18, 2),
    Employee_Id INT,
    EmployeeFirstName VARCHAR(50),
    EmployeeLastName VARCHAR(50),
    Is_Salesperson BIT,
    Stock_Item_Id INT,
    Stock_Item_Name VARCHAR(100),
    Stock_ItemColor VARCHAR(50),
    Stock_Item_Size VARCHAR(20),
    Item_Size VARCHAR(20),
    Stock_ItemPrice DECIMAL(18, 2),
    Customer_Id INT,
    CustomerName VARCHAR(100),
    CustomerCategory VARCHAR(50),
    CustomerContactName VARCHAR(100),
    CustomerPostalCode VARCHAR(20),
    CustomerContactNumber VARCHAR(20),
    City_ID INT,
    City VARCHAR(100),
    State_Province VARCHAR(100),
    Country VARCHAR(100),
    Continent VARCHAR(50),
    Sales_Territory VARCHAR(50),
    Region VARCHAR(50),
    Subregion VARCHAR(50),
    Latest_Recorded_Population INT
);
